modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/Crimix/TheOneKey/issues"
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"

[[mods]]
modId="theonekey"
version="${version}"
displayName="The One Key"
updateJSONURL="${update_url}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/the-one-key"
logoFile="theonekey-logo.png"
credits="To all my friends for putting up with me breaking the server multiple times during testing"
authors="black_dog20"
description='''One keybind to rule them all'''

[[dependencies.theonekey]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.theonekey]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="SERVER"
